#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""Collect entry_point for Janitoo
"""
__license__ = """
    This file is part of Janitoo.

    Janitoo is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Janitoo is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Janitoo. If not, see <http://www.gnu.org/licenses/>.

"""
__author__ = 'Sébastien GALLET aka bibi21000'
__email__ = 'bibi21000@gmail.com'
__copyright__ = "Copyright © 2013-2014-2015 Sébastien GALLET aka bibi21000"

import logging
h = logging.NullHandler()
logger = logging.getLogger(__name__).addHandler(h)

from pkg_resources import iter_entry_points
import argparse

from janitoo.classes import GENRE_DESC, VALUE_DESC

def collect(key, output='txt'):
    if output == 'txt':
        print "-------------------------------------------------------------------------------"
        print "Group : %s" %key
    collected = []
    for entrypoint in iter_entry_points(group = key):
        collected.append("%s" %(entrypoint))
    collected.sort()
    for coll in collected:
        if output=='txt':
            print " %s" %(coll)
        elif output=='short':
            print "%s" %(coll.split(' = ')[0])
        else:
            print "%s" %(coll.replace(' = ','='))
    if output=='txt':
        print ""

def component(key, output='txt'):
    if output == 'txt':
        print "-------------------------------------------------------------------------------"
        print "Component : %s" %key
    for entry in iter_entry_points(group = 'janitoo.components'):
        if entry.name==key:
            compo = entry.load()()
            for val in compo.values:
                if output=='txt':
                    print " %s : %s : %s - %s (%s)" %(val, GENRE_DESC[compo.values[val].genre]['label'], VALUE_DESC[compo.values[val].type]['label'], compo.values[val].help, compo.values[val].default)
                elif output=='short':
                    print "%s" %(val)
                else:
                    print "%s" %(val)

def bus(key, output='txt'):
    if output == 'txt':
        print "-------------------------------------------------------------------------------"
        print "Bus (thread) : %s" %key
    for entry in iter_entry_points(group = 'janitoo.threads'):
        if entry.name==key:
            compo = entry.load()({}, force=True)
            th = entry.load()({}, force=True)
            th.init_bus()
            for val in th.bus.values:
                if output=='txt':
                    print " %s : %s : %s - %s (%s)" %(val, GENRE_DESC[th.bus.values[val].genre]['label'], VALUE_DESC[th.bus.values[val].type]['label'], th.bus.values[val].help, th.bus.values[val].default)
                elif output=='short':
                    print "%s" %(val)
                else:
                    print "%s" %(val)

CORE = ["janitoo.threads", "janitoo.components", "janitoo.values", "janitoo.models"]

FLASK = ["janitoo_flask.blueprint", "janitoo_flask.menu_left", "janitoo_flask.listener", "janitoo_flask.network"]

MANAGER = ["janitoo_manager.blueprint", "janitoo_manager.menu_left", "janitoo_manager.listener", "janitoo_manager.network"]

def jnt_parser():
    parser = argparse.ArgumentParser()
    parser.add_argument('-o', '--output', action='store', help='The format (txt, raw, ...)', choices=['txt', 'raw'], default='txt')
    parser.add_argument('-b', '--bus', action='store', help='Collect values of the bus', default=None)
    parser.add_argument('-c', '--component', action='store', help='Collect values of the compoent', default=None)
    parser.add_argument('-t', '--type', action='store', help='The type of entry-point', choices=['all']+CORE+FLASK+MANAGER, default='all')
    return parser

def main():
    parser = jnt_parser()
    args = parser.parse_args()
    if args.bus != None:
        bus(args.bus, output=args.output)
    elif args.component != None:
        component(args.component, output=args.output)
    elif args.type == "all":
        for mod in CORE+FLASK+MANAGER:
            collect(mod, output=args.output)
    else:
        collect(args.type, output=args.output)
if __name__ == '__main__':
    main()

